export const emptyDummyWindow: chrome.windows.Window = {
  alwaysOnTop: false,
  focused: true,
  height: 1392,
  id: 873776134,
  incognito: false,
  left: 1268,
  state: "normal",
  tabs: [
    {
      active: true,
      audible: false,
      autoDiscardable: true,
      discarded: false,
      groupId: -1,
      height: 1264,
      highlighted: true,
      id: 873776135,
      incognito: false,
      index: 0,
      lastAccessed: 1722680833391.358,
      mutedInfo: {
        muted: false,
      },
      pendingUrl: "chrome://newtab/",
      pinned: false,
      selected: true,
      status: "loading",
      title: "New Tab",
      url: "",
      width: 1278,
      windowId: 873776134,
    },
  ],
  top: 0,
  type: "normal",
  width: 1292,
}

export const dummyWindows: chrome.windows.Window[] = [
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773028,
    incognito: false,
    left: 3316,
    state: "normal",
    tabs: [
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.google.com/favicon.ico",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772871,
        incognito: false,
        index: 0,
        lastAccessed: 1722164632159.708,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title: "Google",
        url: "https://www.google.com/",
        width: 1277,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.youtube.com/s/desktop/780e45f1/img/favicon_32x32.png",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772874,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "YouTube",
        url: "https://www.youtube.com/",
        width: 2048,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.xx.fbcdn.net/rsrc.php/yT/r/aGT3gskzWBf.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772877,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "(16) Facebook",
        url: "https://www.facebook.com/",
        width: 2048,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.wikipedia.org/static/favicon/wikipedia.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772880,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Wikipedia",
        url: "https://www.wikipedia.org/",
        width: 2048,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://abs.twimg.com/favicons/twitter.3.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772883,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "x.com/home",
        url: "https://x.com/home",
        width: 2048,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.cdninstagram.com/rsrc.php/y4/r/QaBlI0OZiks.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772884,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Instagram",
        url: "https://www.instagram.com/",
        width: 2048,
        windowId: 873773028,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.amazon.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772889,
        incognito: false,
        index: 6,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Amazon.com. Spend less. Smile more.",
        url: "https://www.amazon.com/",
        width: 2048,
        windowId: 873773028,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773030,
    incognito: false,
    left: 3316,
    state: "normal",
    tabs: [
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.tiktok.com/favicon.ico",
        groupId: -1,
        height: 976,
        highlighted: false,
        id: 873772893,
        incognito: false,
        index: 0,
        lastAccessed: 1722164643603.452,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "TikTok - Make Your Day",
        url: "https://www.tiktok.com/",
        width: 1278,
        windowId: 873773030,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.licdn.com/aero-v1/sc/h/al2o9zrvru7aqj8e1x2rzsrca",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772897,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "LinkedIn: Log In or Sign Up",
        url: "https://www.linkedin.com/",
        width: 2048,
        windowId: 873773030,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772900,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Netflix",
        url: "https://www.netflix.com/browse",
        width: 2048,
        windowId: 873773030,
      },
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://assets.twitch.tv/assets/favicon-32-e29e246c157142c94346.png",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772911,
        incognito: false,
        index: 3,
        lastAccessed: 1722164648186.598,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title: "Twitch",
        url: "https://www.twitch.tv/",
        width: 1278,
        windowId: 873773030,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773032,
    incognito: false,
    left: 3316,
    state: "normal",
    tabs: [
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.whatsapp.net/rsrc.php/v3/yz/r/ujTY9i_Jhs1.png",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772916,
        incognito: false,
        index: 0,
        lastAccessed: 1722164632196.887,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title: "WhatsApp | Secure and Reliable Free Private Messaging and Calling",
        url: "https://www.whatsapp.com/",
        width: 1278,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://openai.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772920,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "OpenAI",
        url: "https://openai.com/",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://archiveofourown.org/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772923,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Home | Archive of Our Own",
        url: "https://archiveofourown.org/",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://www.fandom.com/f2/assets/favicons/favicon.ico?v=d192e414ef713d8d5d5eb28be8b35345f8b7ebfc",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772926,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Fandom",
        url: "https://www.fandom.com/",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.bing.com/sa/simg/favicon-trans-bg-blue-mg-png.png",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772929,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Bing",
        url: "https://www.bing.com/",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://weather.com/daybreak-home/assets/favicon-32x32.c1752b.png",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772932,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title:
          "National and Local Weather Radar, Daily Forecast, Hurricane and information from The Weather Channel and weather.com",
        url: "https://weather.com/?Goto=Redirected",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://res.cdn.office.net/officehub/images/content/images/favicon_m365-31d62b976c.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772933,
        incognito: false,
        index: 6,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Login | Microsoft 365",
        url: "https://www.office.com/",
        width: 2048,
        windowId: 873773032,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://vk.com/images/icons/favicons/fav_logo.ico?7",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772938,
        incognito: false,
        index: 7,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "VK | Welcome!",
        url: "https://vk.com/",
        width: 2048,
        windowId: 873773032,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773034,
    incognito: false,
    left: 3316,
    state: "normal",
    tabs: [
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://s.pinimg.com/webapp/favicon_48x48-7470a30d.png",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772941,
        incognito: false,
        index: 0,
        lastAccessed: 1722164632185.255,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title: "Pinterest",
        url: "https://www.pinterest.com/",
        width: 1278,
        windowId: 873773034,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.apple.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772944,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Apple",
        url: "https://www.apple.com/",
        width: 2048,
        windowId: 873773034,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://edition.cnn.com/media/sites/cnn/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772949,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Breaking News, Latest News and Videos | CNN",
        url: "https://edition.cnn.com/",
        width: 2048,
        windowId: 873773034,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://www.nytimes.com/vi-assets/static-assets/favicon-d2483f10ef688e6f89e23806b9700298.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772952,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "The New York Times - Breaking News, US News, World News and Videos",
        url: "https://www.nytimes.com/",
        width: 2048,
        windowId: 873773034,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.bbc.com/bbcx/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772955,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title:
          "BBC Home - Breaking News, World News, US News, Sports, Business, Innovation, Climate, Culture, Travel, Video & Audio",
        url: "https://www.bbc.com/",
        width: 2048,
        windowId: 873773034,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773036,
    incognito: false,
    left: 3316,
    state: "minimized",
    tabs: [
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://github.githubassets.com/favicons/favicon-dark.svg",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772958,
        incognito: false,
        index: 0,
        lastAccessed: 1722164632223.112,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title: "GitHub",
        url: "https://github.com/",
        width: 1278,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://pages.ebay.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772959,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Electronics, Cars, Fashion, Collectibles & More | eBay",
        url: "https://www.ebay.com/",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://cdn.prod.website-files.com/6257adef93867e50d84d30e2/62fddf0fde45a8baedcc7ee5_847541504914fd33810e70a0ea73177e%20(2)-1.png",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772962,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Discord - Group Chat That’s All Fun & Games",
        url: "https://discord.com/",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://ae01.alicdn.com/images/eng/wholesale/icon/aliexpress.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772967,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title:
          "AliExpress - Online Shopping for Popular Electronics, Fashion, Home & Garden, Toys & Sports, Automobiles and More.",
        url: "https://best.aliexpress.com/?dp=aa1df372-3e9c-4ba3-8e89-79400d38d275&af=5f979ce5d915b86bee3f7002&aff_fcid=427155ab69e845e9838181718318e803-1722164370827-08274-eEy3FqJ&aff_fsk=eEy3FqJ&aff_platform=link-c-tool&sk=eEy3FqJ&aff_trace_key=427155ab69e845e9838181718318e803-1722164370827-08274-eEy3FqJ&terminal_id=2b4f610300864c10aff70ddb13e35cb3&afSmartRedirect=y",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://open.spotifycdn.com/cdn/images/favicon.0f31d2ea.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772968,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Spotify - Web Player: Music for everyone",
        url: "https://open.spotify.com/",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://st1.zoom.us/zoom.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772973,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "One platform to connect | Zoom",
        url: "https://www.zoom.us/",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.naver.com/favicon.ico?1",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772977,
        incognito: false,
        index: 6,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "NAVER",
        url: "https://www.naver.com/",
        width: 2048,
        windowId: 873773036,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.amazon.co.jp/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772978,
        incognito: false,
        index: 7,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Amazon.co.jp | Books, Apparel, Electronics, Groceries & more",
        url: "https://www.amazon.co.jp/",
        width: 2048,
        windowId: 873773036,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
  {
    alwaysOnTop: false,
    focused: false,
    height: 1104,
    id: 873773038,
    incognito: false,
    left: 3316,
    state: "normal",
    tabs: [
      {
        active: true,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.bbc.com/bbcx/favicon.ico",
        groupId: -1,
        height: 976,
        highlighted: true,
        id: 873772983,
        incognito: false,
        index: 0,
        lastAccessed: 1722164632210.706,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: true,
        status: "complete",
        title:
          "BBC Home - Breaking News, World News, US News, Sports, Business, Innovation, Climate, Culture, Travel, Video & Audio",
        url: "https://www.bbc.com/",
        width: 1278,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://static.canva.com/static/images/favicon-1.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772989,
        incognito: false,
        index: 1,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Home - Canva",
        url: "https://www.canva.com/",
        width: 2048,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://a.espncdn.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772992,
        incognito: false,
        index: 2,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "ESPN - Serving Sports Fans. Anytime. Anywhere.",
        url: "https://www.espn.com/",
        width: 2048,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.healthline.com/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873772999,
        incognito: false,
        index: 3,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Healthline: Medical information and health advice you can trust.",
        url: "https://www.healthline.com/",
        width: 2048,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://wassets.hscicdn.com/static/images/favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873773005,
        incognito: false,
        index: 4,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Today's Cricket Match | Cricket Update | Cricket News | ESPNcricinfo",
        url: "https://www.espncricinfo.com/",
        width: 2048,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl: "https://www.cricbuzz.com/images/cb_favicon.ico",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873773008,
        incognito: false,
        index: 5,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "Live Cricket Score, Schedule, Latest News, Stats & Videos | Cricbuzz.com",
        url: "https://www.cricbuzz.com/",
        width: 2048,
        windowId: 873773038,
      },
      {
        active: false,
        audible: false,
        autoDiscardable: true,
        discarded: false,
        favIconUrl:
          "https://img.lb.wbmdstatic.com/vim/live/webmd/consumer_assets/site_images/favicon/favicon.png",
        groupId: -1,
        height: 983,
        highlighted: false,
        id: 873773013,
        incognito: false,
        index: 6,
        mutedInfo: {
          muted: false,
        },
        pinned: false,
        selected: false,
        status: "complete",
        title: "WebMD - Better information. Better health.",
        url: "https://www.webmd.com/",
        width: 2048,
        windowId: 873773038,
      },
    ],
    top: 0,
    type: "normal",
    width: 1292,
  },
]
